### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by Funcan** [CiscoDevNet/es-logger#1]
According to CONTRIBUTING.md: All contributions to this project will be released under the Apache 2.0 License

The first line of LICENSE.md: MIT License

The MIT and Apache 2.0 licenses are different in intent, see for example https://www.quora.com/Whats-the-difference-between-Apache-v2-0-and-MIT-license-What-are-the-major-consequences-of-using-Apache-software-over-MIT for discussion

**Comment by j3p0uk** [comment]
Corrected to intended MIT License
